Simplified some code
romannurik/muzei pull request #693
Opened 2020-09-21 17:36 UTC by GeorgCantor

2020-09-22 22:30 UTC, ianhanniballake requested changes

2020-09-22 22:30 UTC, ianhanniballake commented on main/src/main/java/com/google/android/apps/muzei/settings/EffectsFragment.kt
> +        binding.toolbar.menu.findItem(R.id.action_link_effects).apply {
Use `with(binding.toolbar.menu.findItem(R.id.action_link_effects))`

2020-09-22 22:30 UTC, ianhanniballake commented on main/src/main/java/com/google/android/apps/muzei/settings/EffectsFragment.kt
> +            }
Switch this back to the previous setup:

1. `when (boolean)` can always be more succinctly written as an if statement
2. Don't `setIcon` as a side effect of setting the title. Keep this as two separate statements. Yes, the two if statements are intentional.

2020-09-23 20:15 UTC, GeorgCantor commented on main/src/main/java/com/google/android/apps/muzei/settings/EffectsFragment.kt
> +        binding.toolbar.menu.findItem(R.id.action_link_effects).apply {
Ok

2020-09-23 21:29 UTC, ianhanniballake approved these changes

2020-09-23 21:30 UTC, merged